name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # Проверка код из реп

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
      # Google Cloud SDK

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
      # Docker для Artifact Registry

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/diplom-433408/test/combined-app:latest .
      # Сборка Docker-образ

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/diplom-433408/test/combined-app:latest
      # Отправляет Docker-образ в Artifact Registry

    - name: Set up kubectl
      uses: google-github-actions/setup-kubectl@v1
      with:
        version: 'latest'
     

    - name: Delete old Kubernetes pods
      run: kubectl delete pods -l app=infisical-backend-new
      
