name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # Проверка код из реп

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
      # Google Cloud SDK
      
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
      # Docker для Artifact Registry

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/diplom-433408/test/combined-app:latest -f Dockerfile.standalone-infisical .
      # Сборка Docker-образ

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/diplom-433408/test/combined-app:latest
      # Отправляет Docker-образ в Artifact Registry
      
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials infisical-cluster --zone us-central1-a
      
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
     

    - name: Delete old Kubernetes pods
      run: kubectl delete pods -l app=infisical-backend-new
      
